[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kano-cv"
version = "1.9.2"
description = "Helpful functions for Computer Vision tasks"
readme = "README.md"
authors = [{ name = "egliette", email = "leminhtu74@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = ["computer vision"]
dependencies = [
    "tqdm>=4.8",
    "numpy>=1.23",
    "pytube>=15.0",
    "opencv-python>=4.9",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "black>=24.2.0",
    "isort>=5.13.2",
    "flake8>=7.0.0",
    "pip-tools>=7.3.0",
    "pytest>=8.0.0",
    "build>=1.0.3",
    "twine>=5.0.0",
    "pre-commit>=3.6.1",
    "python-semantic-release>=9.1.0",
]

[project.urls]
Github = "https://github.com/egliette/kano"

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.semantic_release]
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
version_toml = [
    "pyproject.toml:project.version"
]

[tool.semantic_release.commit_parser_options]
major_tags = ["major"]
minor_types = ["feat"]
patch_types = ["fix"]
